name: 'Assign semester labels to new issues'
description: 'Assign semester labels to new issues'
inputs:

  color:
    description: The color of the label
    default: FFFFFF

outputs:

  label:
    description: The assigned label text
    value: ${{ steps.compute_label.outputs.label }}

runs:

  using: "composite"
  steps:

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Compute label
      id: compute_label
      shell: bash
      run: echo "label=$(compute_label.py)" >> "$GITHUB_OUTPUT"

    - name: Create label
      continue-on-error: true
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createLabel({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: '${{ steps.compute_label.outputs.label }}',
            color: '${{ inputs.color }}'
          });

    - name: Assign label
      continue-on-error: true
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['${{ steps.compute_label.outputs.label }}']
          });