name: Assign semester labels to new issues

on:
  issues:
    types: [opened]

jobs:
  label:
    if: contains(github.event.issue.labels.*.name, '--label-semester-issue-action-test--')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:

      - uses: ./