name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: ['master']
    paths:
      - '.github/workflows/test.yml'
      - '.github/workflows/label.yml'
      - 'action.yml'
      - '**/*.py'
  push:
    paths:
      - '.github/workflows/test.yml'
      - '.github/workflows/label.yml'
      - 'action.yml'
      - '**/*.py'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      # TODO: Create issue with `--label-semester-issue-action-test--` in the name
      # TODO: Assert that a label has been added