name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: ['master']
    paths:
      - '.github/workflows/test.yml'
      - '.github/workflows/label.yml'
      - 'action.yml'
      - '**/*.py'
  push:
    paths:
      - '.github/workflows/test.yml'
      - '.github/workflows/label.yml'
      - 'action.yml'
      - '**/*.py'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Compute the expected label
        uses: kostrykin/current-semester-action@v0.1
        id: semester

      - name: Create issue
        uses: actions/github-script@v7
        id: issue
        with:
          script: |
            const issue = await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '--label-semester-issue-action-test--',
              body: ''
            });
            core.setOutput('number', issue.data.number);

      - name: Check issue labels
        id: labels
        uses: actions/github-script@v7
        with:
          script: |
            const { data: issue } = await github.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.issue.outputs.number }}
            });

            const labels = issue.labels.map(label => label.name);
            const hasLabel = labels.includes('${{ steps.semester.outputs.description }}');

            core.setOutput('has-label', hasLabel);

      - name: Check result
        run: exit 1
        if: ${{ !steps.labels.outputs.has-label }}

      - name: Close issue
        uses: actions/github-script@v7
        with:
          script: |
            await github.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.issue.outputs.number }},
              state: 'closed'
            });